version: '3.2'
services:
  koel:
    # build: . # use this if you want to build on your own
    image: chgu82837/koel
    volumes:
    - &media_path '/path/to/your/media:/media'
    - /usr/src/koel/node_modules
    - ./web/public:/usr/src/koel/public
    env_file: .env
    depends_on:
    - db
  db:
    image: mariadb:10
    env_file: .env
    restart: always
  caddy:
    image: abiosoft/caddy
    ports:
    - '80:80'
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - type: bind
      source: ./web
      target: /usr/src/koel
      read_only: true
  db_client: &db_client
    image: mariadb:10
    depends_on:
    - db
    volumes:
    - .:/tmp/
    env_file: .env
    command: bash
  dump: &db
    <<: *db_client
    command: bash -c 'mysqldump -h $$DB_HOST -u $$DB_USERNAME -p$$DB_PASSWORD $$DB_DATABASE > "/tmp/bak/$$(date +%Y%m%d%H%M%S).sql"'

