version: '3.2'
volumes:
  koel:
    driver: local
services:
  koel:
    # build: . # use this if you want to build on your own
    image: chgu82837/koel
    volumes:
    - &media_path '/path/to/your/media:/media'
    - type: bind
      source: koel
      target: /usr/src/koel
    env_file: .env
    depends_on:
    - db
  db:
    image: mariadb:10
    env_file: .env
  caddy:
    image: abiosoft/caddy
    ports:
    - '80:80'
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - type: mount
      source: koel
      target: /usr/src/koel
      volume:
        nocopy: true
  period_sync:
    # build: . # use this if you want to build on your own
    image: chgu82837/koel
    env_file: .env
    depends_on:
    - db
    - koel
    volumes:
    - *media_path
    - type: mount
      source: koel
      target: /usr/src/koel
      volume:
        nocopy: true
    command: /usr/local/bin/koel_period_sync.sh

